theme: jekyll-theme-time-machine
permalink: /:year/:month/:day/:title.html
paginate: 20
markdown: kramdown

# 作者信息
author: 
  name: Zhong Xin Yan
  email: 18861812263@139.com
  link:  IOT-code-code.github.io
  Wechat: 18861812263
  weibo: http://weibo.com/2459205691/profile?topnav=1&wvr=6
  github: http://github.com/IOT-code-code

  linkedin: 

# 站点信息
title: 高中生闫某
description: My personal blog
url: 
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/me/horse1.jpg
favicon: /public/img/me/horse1.jpg

# google analytics 设置
ga:
  id:  
  url: http://IOT-code-code.github.io/

# disqus 设置  评论框-留言模块
disqus:
  shortname: IOT-code-code

# 主题设置，自动激活某个标签|默认主页显示的分类文章
active: 计算机

# 首页除了最新文章外显示分类
# cates: 
#  - Optimization
#  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档